version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/js'
    schedule:
      interval: weekly
      time: '04:30'
      day: 'monday'
      timezone: 'Pacific/Auckland'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: chromedriver
  - package-ecosystem: 'npm'
    directory: '/ts'
    schedule:
      interval: weekly
      time: '04:30'
      day: 'monday'
      timezone: 'Pacific/Auckland'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: chromedriver
