# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and run tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install npm packages
        run: yarn ci

      - name: Lint app
        if: always()
        run: yarn lint

      - name: Build app
        run: |
          yarn build
          yarn refresh-data

      - name: Start app and run integration tests
        run: |
          ./scripts/docker/run.sh
          yarn test
