name: Java - Javalin - CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'java-javalin/**'
      - '.github/workflows/java-javalin-ci.yaml'

jobs:
  test:
    defaults:
      run:
        working-directory: ./java-javalin
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Use Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test
        run: ./gradlew build --no-daemon
