name: Python - CI

on:
  workflow_call:

jobs:
  changes:
    uses: ./.github/workflows/check-for-changes.yaml
    with:
      filters: |
        requires-check:
          - 'python/**'
          - '.github/workflows/python-ci.yaml'

  test:
    needs: changes
    if: needs.changes.outputs.requires-check == 'true'
    defaults:
      run:
        working-directory: ./python
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install poetry
        run: pipx install poetry

      - name: Install packages
        run: poetry install

      - name: Lint with pylint
        if: always()
        run: poetry run pylint --recursive=y .

      - name: Check style with pycodestyle
        if: always()
        run: poetry run pycodestyle .

      - name: Run tests
        if: always()
        run: poetry run pytest
