name: Typescript - Test - Playwright Mocha

env:
  PASSWORDS: testpassword=${{ secrets.TESTPASSWORD }}

on:
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        working-directory: ./typescript-test-playwright-mocha
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: yarn ci

      - name: Lint project
        if: always()
        run: yarn lint

      - name: Run API tests
        if: always()
        run: yarn test-api

      - name: Run UI tests
        if: always()
        run: ${{ env.PASSWORDS }} yarn test-ui-headless tests/ui
