name: Typescript - Kafka Client - CI

on:
  workflow_call:

jobs:
  changes:
    uses: ./.github/workflows/check-for-changes.yaml
    with:
      filters: |
        requires-check:
          - 'typescript-kafka-client/**'
          - '.github/workflows/typescript-kafka-client-ci.yaml'

  test:
    needs: changes
    if: needs.changes.outputs.requires-check == 'true'
    defaults:
      run:
        working-directory: ./typescript-kafka-client
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: npm run ci

      - name: Lint project
        if: always()
        run: npm run lint

      - name: Build project
        if: always()
        run: npm run build

      - name: Start kafka
        run: ./script/start.sh

      - name: Run tests
        if: always()
        run: npm test

      - name: Stop kafka
        if: always()
        run: ./script/stop.sh
