name: Typescript - Test - Cypress

env:
  PASSWORDS: testpassword=${{ secrets.TESTPASSWORD }}

on:
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        working-directory: ./typescript-test-cypress
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: yarn ci

      - name: Lint project
        if: always()
        run: yarn lint

      - name: Run API tests
        if: always()
        run: yarn test
