name: Typescript - Test - WebdriverIO

env:
  PASSWORDS: testpassword=${{ secrets.TESTPASSWORD }}

on:
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        working-directory: ./typescript-test-webdriverio
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: yarn ci

      - name: Lint project
        if: always()
        run: yarn lint

      - name: Run API tests
        if: always()
        run: ${{ env.PASSWORDS }} yarn test-api

      - name: Run UI tests
        if: always()
        run: ${{ env.PASSWORDS }} yarn test-ui-headless

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'junit/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
