name: Typescript - Test - WebdriverIO

env:
  PASSWORDS: testpassword=${{ secrets.TESTPASSWORD }}

on:
  workflow_dispatch:
  workflow_call:

jobs:
  changes:
    uses: ./.github/workflows/check-for-changes.yaml
    with:
      filters: |
        requires-check:
          - 'typescript-test-webdriverio/**'
          - '.github/workflows/typescript-test-webdriverio-ci.yaml'

  test:
    needs: changes
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.requires-check == 'true'
    defaults:
      run:
        working-directory: ./typescript-test-webdriverio
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: npm run ci

      - name: Lint project
        if: always()
        run: npm run lint

      - name: Run API tests
        if: always()
        run: ${{ env.PASSWORDS }} npm run test-api

      - name: Run UI tests
        if: always()
        run: ${{ env.PASSWORDS }} npm run test-ui-headless

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'junit/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
