name: Typescript - Express Server - CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'typescript-express-server/**'
      - '.github/workflows/typescript-express-server-ci.yaml'

jobs:
  test:
    defaults:
      run:
        working-directory: ./typescript-express-server
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: npm run ci

      - name: Lint app
        if: always()
        run: npm run lint

      - name: Build app
        run: |
          npm run build
          npm run refresh-data

      - name: Start app and run integration tests
        run: |
          ./scripts/docker/run.sh
          npm test
