name: Typescript - Test - Playwright

env:
  PASSWORDS: testpassword=${{ secrets.TESTPASSWORD }}

on:
  pull_request:
    branches: [main]
    paths:
      - 'typescript-test-playwright/**'
      - '.github/workflows/typescript-test-playwright-ci.yaml'

jobs:
  test:
    defaults:
      run:
        working-directory: ./typescript-test-playwright
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: npm run ci

      - name: Lint project
        if: always()
        run: npm run lint

      - name: Run API tests
        if: always()
        run: npm run test-api

      - name: Run UI tests
        if: always()
        run: ${{ env.PASSWORDS }} npm run test-ui
