name: Typescript - Kafka Client - CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'typescript-kafka-client/**'
      - '.github/workflows/typescript-kafka-client-ci.yaml'

jobs:
  test:
    defaults:
      run:
        working-directory: ./typescript-kafka-client
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: npm run ci

      - name: Lint project
        if: always()
        run: npm run lint

      - name: Build project
        if: always()
        run: npm run build

      - name: Start kafka
        run: ./script/start.sh

      - name: Run tests
        if: always()
        run: npm test

      - name: Stop kafka
        if: always()
        run: ./script/stop.sh
